functions:
  "fetch_source":
    - command: git.get_project
      params:
        directory: "mongo-swift-driver"

pre:
  - func: "fetch_source"

tasks:
  - name: compile
    commands:
      - command: shell.exec
        params:
          silent: true
          script: |
            set -e
            export DEVELOPER_DIR=/Applications/Xcode9.2.app
            cd mongo-swift-driver
            make

  - name: run_tests
    commands:
      - command: shell.exec
        silent: true
        params:
          script: |
            set -e
            export DEVELOPER_DIR=/Applications/Xcode9.2.app
            cd mongo-swift-driver
            make test

buildvariants:
- name: osx-1012
  display_name: OS X 10.12
  run_on:
    - macos-1012
  tasks:
    - name: compile
    - name: run_tests
