disabled_rules:
  - file_length
  - function_body_length
  - identifier_name
  - todo
  - type_body_length
  - type_name

opt_in_rules:
  - fatal_error_message
  - implicit_return
  - missing_docs
  - modifier_order 
  - operator_usage_whitespace
  - redundant_type_annotation
  - sorted_imports
  - trailing_closure
  - vertical_parameter_alignment_on_call

excluded:
  - build
  - .build
  - docs
  - Examples/*/build
  - Examples/*/.build
