language: generic
sudo: required
dist: trusty

env:
  global:
    - MONGODB_VERSION=4.2.0
    - LIBMONGOC_VERSION=r1.15
    - LIBMONGOC_CACHE_DIR=${HOME}/libmongoc-${LIBMONGOC_VERSION}

jobs:
  include:
    - stage: pre-tests
      name: verify Linux tests are synced
      os: osx
      install: ./Tests/Scripts/install_dependencies.sh sourcery
      before_script: skip
      script: 
        - make linuxmain SOURCERY=${PWD}/sourcery/bin/sourcery
        - git diff --exit-code Tests/LinuxMain.swift

    - stage: tests
      os: osx
      osx_image: xcode10.2
      env: SWIFT_VERSION=5.0

    - stage: tests
      os: linux
      env: SWIFT_VERSION=5.0

    - stage: post-tests
      name: code coverage
      os: osx
      osx_image: xcode10.2
      script: make coverage
      after_success: bash <(curl -s https://codecov.io/bash)

    - stage: post-tests
      name: lint
      os: osx
      osx_image: xcode11.1
      install: ./Tests/Scripts/install_dependencies.sh swiftlint
      before_script: skip
      script: ${PWD}/swiftlint/swiftlint --strict


install:
  - INSTALLER=Tests/Scripts/install_dependencies.sh
  - ./${INSTALLER} libmongoc
  - ./${INSTALLER} mongodb
  - if [[ "$TRAVIS_JOB_NAME" != "code coverage" ]]; then eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"; fi

before_script:
  - MONGODIR=${PWD}/mongodb-${MONGODB_VERSION}
  - mkdir ${MONGODIR}/data
  - ${MONGODIR}/bin/mongod --dbpath ${MONGODIR}/data --logpath ${MONGODIR}/mongodb.log --fork

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make test-pretty; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make test; fi

cache:
  directories:
    - ${LIBMONGOC_CACHE_DIR}
