language: generic
dist: xenial

env:
  global:
    - MONGODB_VERSION=3.6.14

jobs:
  include:
    - stage: post-tests
      name: code coverage
      os: osx
      osx_image: xcode11.3
      script: make coverage
      after_success: bash <(curl -s https://codecov.io/bash)

install:
  - INSTALLER=etc/install_dependencies.sh
  - ./${INSTALLER} mongodb
  - if [[ "$TRAVIS_JOB_NAME" != "code coverage" ]]; then eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"; fi

before_script:
  - MONGODIR=${PWD}/mongodb-${MONGODB_VERSION}
  - mkdir ${MONGODIR}/data
  - ${MONGODIR}/bin/mongod --dbpath ${MONGODIR}/data --logpath ${MONGODIR}/mongodb.log --fork
